//
// Created by Frode Randers on 2024-10-12.
//

#ifndef ZLOG_H
#define ZLOG_H

#define NUMBER_HEADER_FIELDS    10
#define NUMBER_HEADER_READ_ATTEMPTS 10

#define NOMINAL_BATCH_COUNT 5000L
#define NOMINAL_BATCH_SIZE  1000000L

#define DATE_FORMAT "%Y-%m-%d"

#define STATUS_ENDED_SUCCESSFULLY             0
#define STATUS_ARGUMENTS_MISSING              1
#define STATUS_INVALID_ARGUMENT               2
#define STATUS_GENERAL_FAILURE                3
#define STATUS_ENDED_UNSUCCESSFULLY          10
#define FILE_READ_RELATED_ERRORS            100
#define STATUS_COULD_NOT_OPEN_HEADER_FILE   101
#define STATUS_COULD_NOT_OPEN_PAYLOAD_FILE  102


#endif // ZLOG_H
